version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    env_file:
      - .env
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    networks:
      - mariadb
    volumes:
      - ./mariadb/conf/:/etc/mariadb/conf.d/:ro
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    depends_on:
      - mariadb
    networks:
      - mariadb
      - nginx
    volumes:
      - ./wordpress/conf/:/etc/wordpress/conf.d/:ro
    env_file:
      - .env
    restart: unless-stopped

networks:
  nginx:

  mariadb: