version: '3'

#                                                                                                                                                                                                 _._     _,-'""`-._
# Comments are for tests purpose with official images                                                                                                                                            (,-.`._,'(       |\`-/|
# You can switch between official and non official by switching comments                                                                                                                              `-.-' \ )-`( , o o)
#                                                                                                                                                                                                        `-    \`_`"'- You've been niargoused

services:

  nginx:
    container_name: nginx
#    image: nginx:latest
    build: ./images/nginx
    networks:
      - nginx-network
    ports:
      - 443:443
    volumes:
#      - ./images/nginx/ssl:/etc/nginx/ssl/mycerts:ro
#      - ./images/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    container_name: wordpress
#    image: wordpress:php8.1-fpm
    build: ./images/wordpress
    networks:
      - nginx-network
      - mariadb-network
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
#    image: mariadb:latest
    build: ./images/mariadb
    networks:
      - mariadb-network
    volumes:
     - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env

networks:
  nginx-network:
    driver: bridge

  mariadb-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb_data
      o: bind

  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wp_data
      o: bind
 