version: '3'

services:

  nginx:
    image: nginx:latest
    networks:
      - nginx-network
    ports:
      - 443:443
    volumes:
      - ./images/nginx/ssl:/etc/nginx/ssl/mycerts:ro
      - ./images/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./images/nginx/code/:/code/:ro
    depends_on:
      - wordpress
    restart: unless-stopped

  wordpress:
    image: php:fpm
    networks:
      - nginx-network
    depends_on:
      - mariadb
    volumes:
      - ./images/nginx/code/:/code/:ro
    restart: unless-stopped
    env_file:
      - .env

  mariadb:
    image: mariadb:latest
    networks:
      - nginx-network
    volumes:
     - mysqldata:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env

networks:
  nginx-network:
    driver: bridge

volumes:
  mysqldata:

  wp_data:
 