version: '3'

services:

  nginx:
    image: nginx:latest
    networks:
      - nginx-network
    ports:
      - 443:443
    volumes:
      - ./images/nginx/ssl:/etc/nginx/ssl/mycerts:ro
      - ./images/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./images/nginx/code/:/code/:ro
      - php  
    restart: unless-stopped

  php:
    image: php:fpm
    networks:
      - nginx-network
    volumes:
      - ./images/nginx/code/:/code/:ro

networks:
  nginx-network:
    driver: bridge
 