version: '3'

services:

  nginx:
    image: nginx:latest
    networks:
      - nginx
    ports:
      - 443:443
    volumes:
      - ./images/nginx/ssl:/etc/ssl/:ro
      - ./images/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./images/nginx/html/:/html/:ro
      
    restart: unless-stopped

networks:
  nginx:
 