#!/bin/bash
set -eo pipefail

if [ "$MYSQL_RANDOM_ROOT_PASSWORD" ] && [ -z "$MYSQL_USER" ] && [ -z "$MYSQL_PASSWORD" ]; then
	# there's no way we can guess what the random MySQL password was
	echo >&2 'healthcheck error: cannot determine random root password (and MYSQL_USER and MYSQL_PASSWORD were not set)'
	exit 0
fi

if command -v mysqladmin &> /dev/null; then
	if mysqladmin ping > /dev/null; then
		exit 0
	fi
else
	if select="$(echo 'SELECT 1' | mysql)" && [ "$select" = '1' ]; then
		exit 0
	fi
fi

exit 1